# fly.toml app configuration file generated for sparkling-moon-1321 on 2023-07-22T16:06:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sparkling-moon-1321"
primary_region = "arn"

[experimental]
  auto_rollback = true

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = ""
  internal_port = 8080
  processes = ["app"]
